- name: Install htop on target servers
  hosts: all
  become: yes
  tasks:

    - name: Ensure htop is installed (Debian/Ubuntu)
      apt:
        name: htop
        state: present
        update_cache: yes
      when: ansible_facts['os_family'] == "Debian"

    - name: Ensure htop is installed (RHEL/CentOS)
      yum:
        name: htop
        state: present
      when: ansible_facts['os_family'] == "RedHat"
