- name: Install Apache Tomcat
  hosts: tomcat_servers
  become: yes
  vars:
    tomcat_version: 9.0.85
    tomcat_user: tomcat
    tomcat_install_dir: /opt/tomcat
  tasks:

    - name: Install Java
      apt:
        name: default-jdk
        state: present
        update_cache: yes

    - name: Create Tomcat group
      group:
        name: "{{ tomcat_user }}"

    - name: Create Tomcat user
      user:
        name: "{{ tomcat_user }}"
        shell: /bin/false
        group: "{{ tomcat_user }}"
        create_home: no

    - name: Download Tomcat archive
      get_url:
        url: "https://archive.apache.org/dist/tomcat/tomcat-9/v{{ tomcat_version }}/bin/apache-tomcat-{{ tomcat_version }}.tar.gz"
        dest: /tmp/apache-tomcat-{{ tomcat_version }}.tar.gz

    - name: Create installation directory
      file:
        path: "{{ tomcat_install_dir }}"
        state: directory
        owner: root
        group: root
        mode: '0755'

    - name: Extract Tomcat
      unarchive:
        src: /tmp/apache-tomcat-{{ tomcat_version }}.tar.gz
        dest: "{{ tomcat_install_dir }}"
        remote_src: yes
        creates: "{{ tomcat_install_dir }}/apache-tomcat-{{ tomcat_version }}"

    - name: Change ownership
      file:
        path: "{{ tomcat_install_dir }}/apache-tomcat-{{ tomcat_version }}"
        state: directory
        recurse: yes
        owner: "{{ tomcat_user }}"
        group: "{{ tomcat_user }}"

    - name: Create symbolic link to 'latest'
      file:
        src: "{{ tomcat_install_dir }}/apache-tomcat-{{ tomcat_version }}"
        dest: "{{ tomcat_install_dir }}/latest"
        state: link
        force: yes

    - name: Make startup scripts executable
      file:
        path: "{{ tomcat_install_dir }}/latest/bin/{{ item }}"
        mode: '0755'
      loop:
        - startup.sh
        - shutdown.sh

    - name: Create systemd service file
      copy:
        dest: /etc/systemd/system/tomcat.service
        content: |
          [Unit]
          Description=Apache Tomcat Web Application Container
          After=network.target

          [Service]
          Type=forking

          User={{ tomcat_user }}
          Group={{ tomcat_user }}

          Environment="JAVA_HOME=/usr/lib/jvm/java-11-openjdk-amd64"
          Environment="CATALINA_PID={{ tomcat_install_dir }}/latest/temp/tomcat.pid"
          Environment="CATALINA_HOME={{ tomcat_install_dir }}/latest"
          Environment="CATALINA_BASE={{ tomcat_install_dir }}/latest"

          ExecStart={{ tomcat_install_dir }}/latest/bin/startup.sh
          ExecStop={{ tomcat_install_dir }}/latest/bin/shutdown.sh

          [Install]
          WantedBy=multi-user.target

    - name: Reload systemd
      systemd:
        daemon_reload: yes

    - name: Enable and start Tomcat
      systemd:
        name: tomcat
        enabled: yes
        state: started
